-- total revenue 1
SELECT 
    ROUND(SUM(total_price),2) AS Total_revenue
FROM
    pizza_sales;
-- AVERAGE ORDER VALUE 2 
SELECT 
    ROUND(SUM(total_price) / COUNT(DISTINCT (ORDER_ID)),2) AS AVG_ORDER_VALUE
FROM
    PIZZA_SALES;
-- TOTAL PIZZA SOLD 3
SELECT 
    SUM(QUANTITY) AS TOTAL_PIZZA
FROM
    PIZZA_SALES;    
-- TOTAL ORDER  4
SELECT 
    COUNT(DISTINCT(ORDER_ID)) AS TOTAL_PIZZA
FROM
    PIZZA_SALES;
-- AVERAGE PIZZA PER ORDER 5
SELECT 
    SUM(QUANTITY) / COUNT(DISTINCT (ORDER_ID)) AS AVG_PIZZA_SOLD
FROM
    pizza_sales;
-- TOTAL ORDERS BY DAYSNAME 6
SELECT 
    DAYNAME(ORDER_DATE) AS DAY,
    COUNT(DISTINCT (ORDER_ID)) AS ORDERS
FROM
    pizza_sales
GROUP BY DAY;
-- TOTAL ORDERS BY MONTHWISE 7
SELECT 
    MONTHNAME(ORDER_DATE) AS MONTH,
    COUNT(DISTINCT (ORDER_ID)) AS ORDERS
FROM
    PIZZA_SALES
GROUP BY MONTH
ORDER BY ORDERS DESC;
-- PCT OF SALES BY PIZZA CATEGORY 8
SELECT 
    PIZZA_CATEGORY,
    ROUND(SUM(TOTAL_PRICE)) AS SALES,
    ROUND(SUM(TOTAL_PRICE) / (SELECT 
                    SUM(TOTAL_PRICE)
                FROM
                    PIZZA_SALES) * 100) AS PCT
FROM
    PIZZA_SALES
GROUP BY PIZZA_CATEGORY;
-- PCT OF SALES BY PIZZA SIZE 9
SELECT * FROM pizza_sales;
SELECT 
    PIZZA_SIZE,
    ROUND(SUM(TOTAL_PRICE)) AS SALES,
    ROUND(SUM(TOTAL_PRICE) / (SELECT 
                    SUM(TOTAL_PRICE)
                FROM
                    PIZZA_SALES) * 100) AS PCT
FROM
    pizza_sales
GROUP BY PIZZA_SIZE;
-- TOTAL PIZZA SOLD BY PIZZA CATEGORY FOR PARTICULAR MONTH 10
SELECT 
    PIZZA_CATEGORY, SUM(QUANTITY) AS PIZZA_SOLD
FROM
    PIZZA_SALES
WHERE
    MONTH(ORDER_DATE) = 6
GROUP BY PIZZA_CATEGORY;
-- TOP 5 PIZZA BY REVENUE 11
SELECT 
    pizza_name, ROUND(SUM(total_price)) AS Revenue
FROM
    pizza_sales
GROUP BY pizza_name
ORDER BY Revenue DESC
LIMIT 5;
-- LAST 5 PIZZA BY REVENUE 12
SELECT 
    pizza_name, ROUND(SUM(total_price)) AS Revenue
FROM
    pizza_sales
GROUP BY pizza_name
ORDER BY Revenue ASC
LIMIT 5;
-- TOP 5 PIZZA BY QUANTITY 13
SELECT 
    pizza_name, SUM(quantity) AS Quantity
FROM
    pizza_sales
GROUP BY pizza_name
ORDER BY Quantity DESC
LIMIT 5;
-- LAST 5 PIZZA BY QUANTITY 14
SELECT 
    pizza_name, SUM(quantity) AS Quantity
FROM
    pizza_sales
GROUP BY pizza_name
ORDER BY Quantity ASC
LIMIT 5;
-- TOP 5 PIZZA BY ORDERS 15
SELECT 
    pizza_name, COUNT(DISTINCT (order_id)) AS orders
FROM
    pizza_sales
GROUP BY pizza_name
ORDER BY orders DESC
LIMIT 5;
-- LAST 5 PIZZA BY ORDERS 16
SELECT 
    pizza_name, COUNT(DISTINCT (order_id)) AS orders
FROM
    pizza_sales
GROUP BY pizza_name
ORDER BY orders ASC
LIMIT 5;    